### ISSUE TITLE
bundleMetadataFiles on windows, uses backslashes in module names

### ISSUE THREAD

**Issue by roblourens** [Microsoft/vscode-nls#19]
- Clone https://github.com/microsoft/vscode-chrome-debug-core
- Run `gulp transifex-push-test`
- See entries like `<file original="out/src\errors"`

When I pull from Transifex on a mac, I get files with backslashes in their names, because they are not interpreted as directory separators

**Comment by roblourens** [comment]
@dbaeumer Can you tell whether there's something wrong with my configuration that's causing this? I don't get this for the other debug repos, which have simpler gulpfiles, but I shouldn't have to fix the slashes outside of vscode-nls-dev.

**Comment by dbaeumer** [comment]
I will have a look. Usually we combine paths with path.join to avoid these problems.

**Comment by roblourens** [comment]
On windows path.join use backslashes, this is only happening from windows.

**Comment by dbaeumer** [comment]
Fixed in vscode-nls-dev. The problem was that we correctly used '/' even on windows to combine things but we didn't change the slash in the path under Windows.
