### ISSUE TITLE
Use fs.readFile instead of require

### ISSUE THREAD

**Issue by jrieken** [Microsoft/vscode-nls#20]
Today vscode-nls uses require to read JSON files, e.g. [`require(path.join(folder, 'nls.metadata.json'))`](https://github.com/Microsoft/vscode-nls/blob/a588022d7175a42958a680d6cc9322c85ca54263/src/main.ts#L295). Constructs like this prevent this module from being webpack-able and we should avoid them, e.g. by using `readFile` and `JSON.parse`

**Comment by dbaeumer** [comment]
This got addressed a while ago.
