### ISSUE TITLE
Bundled nls doesn't work

### ISSUE THREAD

**Issue by IlyaBiryukov** [microsoft/vscode-nls#23]
vscode-nls version 4.0.0.

**Repro:**
In a 3rd party extension:
1. Build produces `nls.bundle.*.json` files in the out folder
2. Extension code uses `const localize = nls.loadMessageBundle()` where nls comes from `import * as nls from 'vscode-nls';`
`loadMessageBundle` calls `loadNlsBundle()` which hits this code:
```typescript
    ...
    if (!result) {
        // No language pack found, but core is running in language pack mode
        // Don't try to use old in the box bundles since the might be stale
        // Fall right back to the default bundle.
        if (options.languagePackSupport) {
            return loadDefaultNlsBundle(bundlePath);
        }
```
4. Default nls bundle is loaded always even when language-specific bundles exist .

**Workaround**
There is no way `options.languagePackSupport` can be configured via `nls.config()`.
The only ugly workaround is to change `process.env.VSCODE_NLS_CONFIG` and set `_languagePackSupport` to false before loading the `vscode-nls` module. 

**Impact:**
3rd party extensions cannot use nls bundles.

**Comment by IlyaBiryukov** [comment]
@dbaeumer ping?

**Comment by dbaeumer** [comment]
@IlyaBiryukov sorry that slipped through the cracks. My proposal is to add an additional option to force the old `nls.bundle`. See

https://github.com/microsoft/vscode-nls/commit/f69240ba39e37479277b4ee87808b8edc0a7da3c

Would that work for you?

**Comment by IlyaBiryukov** [comment]
@dbaeumer yep, that will work

**Comment by dbaeumer** [comment]
Publish 4.1.1.

Let me know how it goes.

**Comment by IlyaBiryukov** [comment]
I may get to upgrading it in our extension next week. I'll get back and report how it goes.
