### ISSUE TITLE
localize calls cache the locale

### ISSUE THREAD

**Issue by digeff** [microsoft/vscode-nls#26]
I'm trying to use the library inside of a debug-adapter for Visual Studio, which doesn't set VSCODE_NLS_CONFIG.

From the experiments I've run it seems that localize the result of nls.loadMessageBundle(); is caching the locale when the function is called, and that if I change the locale with nls.config({ locale: 'de-DE' }) after a call to nls.loadMessageBundle() is made, the localize function is stuck on the initial locale, and not the one I configured with nls.config (A new call to nls.loadMessageBundle() returns localize with the new locale, but the already created localize functions all use the old locale).

Is there any way for me to make all the localize functions automatically change to the new locale when nls.config is called?

@dbaeumer

**Comment by dbaeumer** [comment]
@digeff you should be able to configure the language to use during the config call. The options are here: https://github.com/Microsoft/vscode-nls/blob/master/src/main.ts#L45

The module currently only supports to configure the language once using the config call. This has to happen in the main JS file before and localize call is made. In the other files only use `nls.loadMessageBundle()` to load the file specific message bundle. 

Please ping if this doesn't address the issue you are seeing.
