### ISSUE TITLE
Can't write corrupted.info file

### ISSUE THREAD

**Issue by dbaeumer** [microsoft/vscode-nls#27]
For the details see: https://github.com/microsoft/vscode/issues/86140

@Tyriar can you please check whether the directory the nls library wants to write that file exists ?

**Comment by Tyriar** [comment]
It's not happening anymore 🤷‍♂

**Comment by dbaeumer** [comment]
Does the directory that failed yesterday exist on your disk. I only clean this up after a couple of weeks and if it doesn't it would explain the failure. But still unclear why it doesn't exist since the main creates it and only passes it to the renderer / extension on successful creation.

**Comment by Tyriar** [comment]
The directory doesn't exist anymore. I can confirm a corrupted.info did not exist, but I'm not 100% sure if the folder I was checking had the same hash in its name as the errors were complaining about when it happened.

**Comment by Tyriar** [comment]
@dbaeumer did you meant to milestone/close this off?

**Comment by dbaeumer** [comment]
Yes, can be closed since I publish a new version.
