### ISSUE TITLE
Failed to load message bundle. See console for details.

### ISSUE THREAD

**Issue by lion9** [microsoft/vscode-nls#38]
I am calling 

`const localize = nls.config({ messageFormat: nls.MessageFormat.file })();`

in my extension.ts

and then, in other files, I am calling

```
let localize = nls.loadMessageBundle();

....

  const message: string = localize(
    "logoutMessage.text",
    "Successfully logged out from Machine Translation Service."
  );
  window.showInformationMessage(message);
```

However, when actually building my extension, I am getting "Failed to load message bundle. See console for details." I am unable to find any output in the console. What might cause this message?

**Comment by dbaeumer** [comment]
@yu3wen thanks for the answer which is correct. The example here https://github.com/microsoft/vscode-extension-samples/blob/d546364e1e0a2f14d9356564a116ea3579035623/i18n-sample/src/extension.ts#L5 shows that.

This order is only necessary in the main file. In the others the import order can be different.

**Comment by dbaeumer** [comment]
I updated the readme to make this clear.
